### ISSUE TITLE
Same_Coce_different_Computer_problem

### ISSUE THREAD

**Issue by Mehmet5353** [genn-team/genn#481]
(env) [hilmi@fedora flash]$  /usr/bin/env /home/hilmi/env/bin/python3.6 /home/hilmi/.vscode/extensions/ms-python.python-2021.11.1422169775/pythonFiles/lib/python/debugpy/launcher 40235 -- /run/media/hilmi/flash/3_different_random_neuron.py 
swig/python detected a memory leak of type 'CodeGenerator::SingleThreadedCPU::Backend *', no destructor found.
make: Entering directory '/run/media/hilmi/flash/pygenn_CODE'
make: g++: Böyle bir dosya ya da dizin yok
make: *** [Makefile:18: customUpdate.o] Error 127
make: Leaving directory '/run/media/hilmi/flash/pygenn_CODE'
Traceback (most recent call last):
  File "/run/media/hilmi/flash/3_different_random_neuron.py", line 72, in <module>
    v=my_model(i)
  File "/run/media/hilmi/flash/3_different_random_neuron.py", line 50, in my_model
    model.build()
  File "/home/hilmi/env/lib64/python3.6/site-packages/pygenn/genn_model.py", line 583, in build
    check_call(["make", "-j", str(cpu_count(logical=False)), "-C", output_path])
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '6', '-C', './pygenn_CODE']' returned non-zero exit status 2.

I got this erros in my computer, but i run very comfortably in my work PC. Can you help

 me? How can i solve this problem

![Ekran görüntüsü 2021-11-16 17-58-46](https://user-images.githubusercontent.com/44751934/142009865-84337c34-d3e0-4ff5-9224-715d61df2a4a.png)

**Comment by Mehmet5353** [comment]
I solved the problem. Sorry to bother
